version: "3"
services: 
  traefik:
    container_name: traefik-container
    image: traefik:v3.0
    hostname: traefik
    volumes:
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    ports: 
      - '80:80'
    networks:
      - survey-api

  redis:
    container_name: redis-container
    image: redis
    hostname: redis
    ports: 
      - '6380:6379'
    networks:
      - survey-api

  mongo:
    container_name: mongo-container
    image: mongo:4
    hostname: mongo
    restart: always
    volumes: 
      - db-data:/data/db/
    ports: 
      - '27019:27017'
    networks:
      - survey-api

  api:
    container_name: api-container
    build: .
    image: survey-api
    hostname: api
    working_dir: /usr/src/clean-node-api
    entrypoint: npm run debug
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - API_HOST=api
      - PORT=7000
    volumes: 
      - ./dist/:/usr/src/clean-node-api/dist/
    ports: 
      - 7000
      - '9222:9222'
    depends_on:
      - mongo
      - redis
    networks:
      - survey-api

  dbgate:
    container_name: dbgate-container
    image: dbgate/dbgate
    hostname: dbgate
    restart: always
    ports:
      - 3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1,con2
      LABEL_con1: Redis
      LABEL_con2: MongoDB
      URL_con1: redis://default:AbcD1234@redis:6379
      URL_con2: mongodb://mongo:27017/survey-api
      ENGINE_con1: redis@dbgate-plugin-redis
      ENGINE_con2: mongo@dbgate-plugin-mongo
    depends_on:
      - mongo
      - redis
    networks:
      - survey-api

networks:
  survey-api:
    driver: bridge
    name: survey-api
    
volumes:
  dbgate-data:
    driver: local
  db-data:
