@host = http://localhost:5000/api
@contentType = application/json
@authToken = {{login.response.body.$.accessToken}}


############################################################

# @name login
POST {{host}}/signup HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Luan Rafael",
  "email": "luanrafaelberto@gmail.com",
  "password": "123",
  "passwordConfirmation": "123"
}

####################

# @name login
POST {{host}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "luanrafaelberto@gmail.com",
  "password": "123"
}

############################################################

GET {{host}}/user/surveys HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{authToken}}

####################

POST {{host}}/publisher/surveys HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{authToken}}

{
  "question": "Question",
  "answers": [{
    "answer": "Answer 1",
    "image": "http://image-name.com"
  }, {
    "answer": "Answer 2"
  }]
}

############################################################
