name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.16
      uses: actions/setup-node@v3
      with:
        node-version: 18.16
        
    - name: Install dependencies
      run: |
        npm pkg delete scripts.prepare
        npm install
        npm run lint:fix
        npm run build

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.9.0

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0

    - name: Starting and check if the server is ok
      run: npm start & sleep 15 && node dist/infra/http/requests/check-server-is-ok.js pipeline_action

    #- name: Run docker
      #run: |
        #docker-compose up --build -d mongo redis api traefik
        #sleep 25 && node dist/infra/http/requests/check-server-is-ok.js pipeline_action 80 127.0.0.1

    #- name: Run coverage tests
      #run: npm run test:ci

    #- name: Coveralls
      #uses: coverallsapp/github-action@v2
      
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /usr/src/survey-api
          git restore .
          git pull -f origin dev
          npm pkg delete scripts.prepare
          npm install
          npm run build
          cd ../survey-api-deploy
          docker compose down --volumes
          docker compose up --build -d
