name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.16
      uses: actions/setup-node@v3
      with:
        node-version: 18.16
        
    - name: Install dependencies and run coverage tests
      run: |
        npm pkg delete scripts.prepare
        npm install
        npm run lint:fix
        npm run test:ci
        npm run build

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.9.0

    - name: Starting and check if the server is ok
      run: npm start & sleep 12 && node dist/infra/http/requests/check-server-is-ok.js pipeline_action

    - name: Run docker
      run: |
        docker-compose up --build -d mongo api
        sleep 25 && node dist/infra/http/requests/check-server-is-ok.js pipeline_action 5000

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /usr/src/survey-api
          git pull origin dev
          npm pkg delete scripts.prepare
          npm install
          npm run build
          cd ../survey-api-deploy
          docker compose down
          docker compose up --build -d
